name: flutter_application_3
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  day_night_switcher: ^0.2.0+1
  concentric_transition: ^1.0.3
  lottie: ^2.6.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  animated_text_kit: ^4.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  table_calendar: ^3.0.9
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2
  flutter_datetime_picker_plus: ^2.1.0
  youtube_player_flutter: ^8.1.2
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

